name: SecondLineAPI
version: ${project.version}
main: net.blitzcube.line2.SecondLineAPI
depend: [ProtocolLib]
authors: [iso2013]
description: An API which allows you to set text to display below the players name
commands:
    secondline:
        description: SecondLine API Demonstration Command
        permission: secondlineapi.test
permissions:
    secondlineapi:
        test:
            default: op
            description: Allows use of the SecondLine API Demonstration Command